"""Module scaffolding tool for generating new Flutter modules.

Generates complete module structure following the PRD specification
with boilerplate, tests, and documentation.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence



# Template definitions
TEMPLATES: dict[str, dict[str, str]] = {
    "minimal": {
        "description": "Basic module shell with ModuleDescriptor",
        "files": ["module_descriptor", "pubspec", "readme"],
    },
    "list-detail": {
        "description": "CRUD pattern with List + Detail + Form screens",
        "files": ["module_descriptor", "list_screen", "detail_screen", "form_screen", "pubspec", "readme"],
    },
    "form-module": {
        "description": "Data capture with validation and offline queue",
        "files": ["module_descriptor", "form_screen", "service", "pubspec", "readme"],
    },
    "content-module": {
        "description": "Display focused with rich text, media, offline cache",
        "files": ["module_descriptor", "list_screen", "detail_screen", "service", "pubspec", "readme"],
    },
    "integration": {
        "description": "External service with abstraction + provider",
        "files": ["module_descriptor", "service_abstract", "service_impl", "pubspec", "readme"],
    },
}


@dataclass
class ModuleConfig:
    """Configuration for module generation."""

    name: str
    template: str
    routes: list[str]
    gates: list[str]
    version: str = "1.0.0"

    @property
    def module_id(self) -> str:
        """Extract module ID from name (e.g., module_blog -> blog)."""
        return self.name.replace("module_", "")

    @property
    def class_name(self) -> str:
        """Generate PascalCase class name."""
        parts = self.module_id.split("_")
        return "".join(p.capitalize() for p in parts) + "Module"

    @property
    def package_name(self) -> str:
        """Generate Dart package name."""
        return self.name.lower().replace("_", "_")


def to_pascal_case(s: str) -> str:
    """Convert snake_case to PascalCase."""
    return "".join(word.capitalize() for word in s.split("_"))


def to_camel_case(s: str) -> str:
    """Convert snake_case to camelCase."""
    parts = s.split("_")
    return parts[0] + "".join(word.capitalize() for word in parts[1:])


def generate_module_descriptor(config: ModuleConfig) -> str:
    """Generate the main module descriptor file."""
    route_definitions = []
    nav_entries = []

    for i, route in enumerate(config.routes):
        # Parse route pattern
        if ":" in route:
            # Parameterized route
            param_name = route.split(":")[-1].rstrip("/")
            route_clean = route.replace(f":{param_name}", f"{{${to_camel_case(param_name)}}}")
        else:
            route_clean = route
            param_name = None

        screen_class = f"{to_pascal_case(config.module_id)}{to_pascal_case(route.split('/')[-1].split(':')[0])}Screen"

        route_definitions.append(f'''    RouteDefinition(
      route: '{route_clean}',
      builder: (_) => const {screen_class}(),
      gates: {config.gates if config.gates else "const []"},
    ),''')

        if i == 0:  # Add navigation entry for first route
            nav_entries.append(f'''    MenuEntry(
      label: '{to_pascal_case(config.module_id)}',
      route: '{route_clean}',
      iconName: 'folder',
      gates: {config.gates if config.gates else "const []"},
    ),''')

    routes_str = "\n".join(route_definitions) if route_definitions else "    // Add routes here"
    nav_str = "\n".join(nav_entries) if nav_entries else "    // Add navigation entries here"

    return f'''import 'package:module_sdk/module_sdk.dart';

/// {to_pascal_case(config.module_id)} module for the wrapper app.
///
/// Generated by: automation.create-module
/// Version: {config.version}
class {config.class_name} extends ModuleDescriptor {{
  @override
  String get id => '{config.module_id}';

  @override
  String get version => '{config.version}';

  @override
  String get displayName => '{to_pascal_case(config.module_id)}';

  @override
  List<FeatureKey> get requiredFeatures => {config.gates if config.gates else "const []"};

  @override
  List<RouteDefinition> get routes => [
{routes_str}
  ];

  @override
  List<MenuEntry> get navigation => [
{nav_str}
  ];

  @override
  Future<void> initialize(ModuleContext ctx) async {{
    // Module initialization
    ctx.analytics.track('{config.module_id}_module_initialized');
  }}
}}
'''


def generate_list_screen(config: ModuleConfig) -> str:
    """Generate a list screen template."""
    return f'''import 'package:flutter/material.dart';

/// List screen for {config.module_id} module.
class {to_pascal_case(config.module_id)}ListScreen extends StatelessWidget {{
  const {config.class_name}ListScreen({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      appBar: AppBar(
        title: const Text('{to_pascal_case(config.module_id)}'),
      ),
      body: ListView.builder(
        itemCount: 10,
        itemBuilder: (context, index) {{
          return ListTile(
            leading: const Icon(Icons.folder),
            title: Text('Item ${{index + 1}}'),
            subtitle: Text('Description for item ${{index + 1}}'),
            onTap: () {{
              // Navigate to detail
            }},
          );
        }},
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {{
          // Navigate to create/edit form
        }},
        child: const Icon(Icons.add),
      ),
    );
  }}
}}
'''


def generate_detail_screen(config: ModuleConfig) -> str:
    """Generate a detail screen template."""
    return f'''import 'package:flutter/material.dart';

/// Detail screen for {config.module_id} module.
class {to_pascal_case(config.module_id)}DetailScreen extends StatelessWidget {{
  const {config.class_name}DetailScreen({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      appBar: AppBar(
        title: const Text('Detail'),
        actions: [
          IconButton(
            icon: const Icon(Icons.edit),
            onPressed: () {{
              // Edit action
            }},
          ),
          IconButton(
            icon: const Icon(Icons.delete),
            onPressed: () {{
              // Delete action
            }},
          ),
        ],
      ),
      body: const Padding(
        padding: EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Title',
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 16),
            Text(
              'Detail content goes here...',
              style: TextStyle(fontSize: 16),
            ),
          ],
        ),
      ),
    );
  }}
}}
'''


def generate_form_screen(config: ModuleConfig) -> str:
    """Generate a form screen template."""
    return f'''import 'package:flutter/material.dart';

/// Form screen for {config.module_id} module.
class {to_pascal_case(config.module_id)}FormScreen extends StatefulWidget {{
  const {config.class_name}FormScreen({{super.key}});

  @override
  State<{to_pascal_case(config.module_id)}FormScreen> createState() => _{to_pascal_case(config.module_id)}FormScreenState();
}}

class _{to_pascal_case(config.module_id)}FormScreenState extends State<{to_pascal_case(config.module_id)}FormScreen> {{
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();

  @override
  void dispose() {{
    _titleController.dispose();
    super.dispose();
  }}

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      appBar: AppBar(
        title: const Text('New Item'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(
                  labelText: 'Title',
                  hintText: 'Enter title',
                ),
                validator: (value) {{
                  if (value == null || value.isEmpty) {{
                    return 'Please enter a title';
                  }}
                  return null;
                }},
              ),
              const SizedBox(height: 24),
              ElevatedButton(
                onPressed: _submit,
                child: const Text('Submit'),
              ),
            ],
          ),
        ),
      ),
    );
  }}

  void _submit() {{
    if (_formKey.currentState!.validate()) {{
      // Submit form
      Navigator.pop(context);
    }}
  }}
}}
'''


def generate_service(config: ModuleConfig) -> str:
    """Generate a service class template."""
    return f'''import 'package:flutter/foundation.dart';

/// Service for {config.module_id} module.
class {to_pascal_case(config.module_id)}Service {{
  /// Fetch all items.
  Future<List<Map<String, dynamic>>> fetchItems() async {{
    // TODO: Implement API call
    await Future.delayed(const Duration(seconds: 1));
    return [];
  }}

  /// Fetch a single item by ID.
  Future<Map<String, dynamic>?> fetchItem(String id) async {{
    // TODO: Implement API call
    await Future.delayed(const Duration(milliseconds: 500));
    return null;
  }}

  /// Create a new item.
  Future<String> createItem(Map<String, dynamic> data) async {{
    // TODO: Implement API call
    await Future.delayed(const Duration(seconds: 1));
    return 'new_item_id';
  }}

  /// Update an existing item.
  Future<void> updateItem(String id, Map<String, dynamic> data) async {{
    // TODO: Implement API call
    await Future.delayed(const Duration(milliseconds: 500));
  }}

  /// Delete an item.
  Future<void> deleteItem(String id) async {{
    // TODO: Implement API call
    await Future.delayed(const Duration(milliseconds: 500));
  }}
}}
'''


def generate_pubspec(config: ModuleConfig) -> str:
    """Generate pubspec.yaml template."""
    return f'''name: {config.package_name}
description: {to_pascal_case(config.module_id)} module for the wrapper app
version: {config.version}
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  module_sdk:
    path: ../module_sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
'''


def generate_readme(config: ModuleConfig) -> str:
    """Generate README.md template."""
    routes_section = "\n".join(f"- `{route}`" for route in config.routes) if config.routes else "- `/module_{config.module_id}`"
    gates_section = "\n".join(f"- `{gate}`" for gate in config.gates) if config.gates else "None"

    return f'''# {to_pascal_case(config.module_id)} Module

{to_pascal_case(config.module_id)} module for the wrapper app.

Generated by automation.create-module v{config.version}

## Routes

{routes_section}

## Feature Gates

{gates_section}

## Usage

```dart
import 'package:{config.package_name}/{config.package_name}.dart';

// Register in module_registry.dart
final kModules = [
  ...,
  {config.class_name}(),
];
```

## Development

### Run tests

```bash
flutter test
```

### Generate golden files

```bash
flutter test --update-goldens
```
'''


def generate_module_config(config: ModuleConfig) -> str:
    """Generate module_config.json metadata file."""
    return json.dumps({
        "name": config.module_id,
        "class_name": config.class_name,
        "package_name": config.package_name,
        "version": config.version,
        "template": config.template,
        "routes": config.routes,
        "gates": config.gates,
        "generated_at": "2025-01-01T00:00:00Z",
    }, indent=2)


def create_module_structure(
    config: ModuleConfig, output_dir: Path, dry_run: bool = False
) -> list[Path]:
    """Create complete module structure.

    Args:
        config: Module configuration
        output_dir: Output directory for the module
        dry_run: If True, don't actually create files

    Returns:
        List of created file paths
    """
    module_dir = output_dir / config.name
    lib_dir = module_dir / "lib" / "src"
    screens_dir = lib_dir / "screens"
    widgets_dir = lib_dir / "widgets"
    services_dir = lib_dir / "services"
    test_dir = module_dir / "test"
    l10n_dir = module_dir / "lib" / "l10n"

    created_files: list[Path] = []

    if not dry_run:
        # Create directories
        for dir_path in [lib_dir, screens_dir, widgets_dir, services_dir, test_dir, l10n_dir]:
            dir_path.mkdir(parents=True, exist_ok=True)

    # Generate files based on template
    template_config = TEMPLATES.get(config.template, TEMPLATES["minimal"])

    files_to_generate: dict[Path, str] = {}

    if "module_descriptor" in template_config["files"]:
        files_to_generate[lib_dir.parent / f"{config.module_id}_module.dart"] = generate_module_descriptor(config)

    if "list_screen" in template_config["files"]:
        files_to_generate[screens_dir / f"{config.module_id}_list_screen.dart"] = generate_list_screen(config)

    if "detail_screen" in template_config["files"]:
        files_to_generate[screens_dir / f"{config.module_id}_detail_screen.dart"] = generate_detail_screen(config)

    if "form_screen" in template_config["files"]:
        files_to_generate[screens_dir / f"{config.module_id}_form_screen.dart"] = generate_form_screen(config)

    if "service" in template_config["files"]:
        files_to_generate[services_dir / f"{config.module_id}_service.dart"] = generate_service(config)

    # Always generate these
    files_to_generate[module_dir / "pubspec.yaml"] = generate_pubspec(config)
    files_to_generate[module_dir / "README.md"] = generate_readme(config)
    files_to_generate[module_dir / "module_config.json"] = generate_module_config(config)

    if not dry_run:
        for file_path, content in files_to_generate.items():
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)

    created_files.extend(files_to_generate.keys())
    return created_files


def main(argv: Sequence[str] | None = None) -> int:
    """Main entry point for CLI."""
    parser = argparse.ArgumentParser(
        prog="create-module",
        description="Generate a new Flutter module for the wrapper app",
    )
    parser.add_argument(
        "--name",
        required=True,
        help="Module name (e.g., module_blog, inventory)",
    )
    parser.add_argument(
        "--template",
        choices=list(TEMPLATES.keys()),
        default="minimal",
        help="Module template to use",
    )
    parser.add_argument(
        "--routes",
        help="Comma-separated routes (e.g., '/blog,/blog/:id')",
    )
    parser.add_argument(
        "--gates",
        help="Comma-separated feature gates (e.g., 'blog.view,blog.create')",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("packages"),
        help="Output directory for the module (default: packages/)",
    )
    parser.add_argument(
        "--version",
        default="1.0.0",
        help="Module version (default: 1.0.0)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be created without creating files",
    )
    parser.add_argument(
        "--list-templates",
        action="store_true",
        help="List available templates",
    )

    args = parser.parse_args(argv)

    # List templates
    if args.list_templates:
        print("\nAvailable Templates:")
        print("-" * 50)
        for name, info in TEMPLATES.items():
            print(f"\n{name}:")
            print(f"  {info['description']}")
            print(f"  Files: {', '.join(info['files'])}")
        return 0

    # Validate module name
    if not args.name.startswith("module_") and not args.name.replace("_", "").isalnum():
        print(f"Error: Invalid module name '{args.name}'", file=sys.stderr)
        print("Module name should be snake_case and contain only letters, numbers, and underscores.", file=sys.stderr)
        return 1

    # Ensure name has module_ prefix
    name = args.name if args.name.startswith("module_") else f"module_{args.name}"

    # Parse routes and gates
    routes = [r.strip() for r in args.routes.split(",")] if args.routes else []
    gates = [g.strip() for g in args.gates.split(",")] if args.gates else []

    config = ModuleConfig(
        name=name,
        template=args.template,
        routes=routes,
        gates=gates,
        version=args.version,
    )

    # Check if module already exists
    module_dir = args.output / name
    if module_dir.exists() and not args.dry_run:
        print(f"Error: Module directory already exists: {module_dir}", file=sys.stderr)
        return 1

    # Create module
    if args.dry_run:
        print(f"\n[Dry Run] Would create module: {name}")
        print(f"Location: {module_dir}")
        print(f"Template: {args.template}")
        print(f"Routes: {routes}")
        print(f"Gates: {gates}")
        return 0

    try:
        created_files = create_module_structure(config, args.output)

        print(f"\n✓ Created module: {name}")
        print(f"Location: {module_dir}")
        print(f"Template: {args.template}")
        print(f"\nFiles created:")
        for file_path in sorted(created_files):
            print(f"  {file_path.relative_to(args.output)}")

        print(f"\nNext steps:")
        print(f"  1. cd {module_dir}")
        print(f"  2. Implement the TODOs in the generated files")
        print(f"  3. Add to apps/wrapper_app/lib/module_registry.dart:")
        print(f"     {config.class_name}(),")
        print(f"  4. flutter test")

        return 0

    except Exception as e:
        print(f"Error creating module: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
